name: "logisticotrain"

services:

  restapi:
    image: restapi
    build:
      context: ./RESTApi
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    depends_on:
      sqldatabase:
        condition: service_healthy
      nosqldatabase:
        condition: service_healthy
    networks:
      - db-net
    environment:
      - SQLDB_HOST=sqldatabase
      - MONGODB_HOST=nosqldatabase
    volumes:
      - ./RESTApi/config.py:/app/config.py
      - ./init-mariadb.sql:/docker-entrypoint-initdb.d/init-mariadb.sql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/api/v1/rames" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    configs:
      - source: init-sql-db
        target: /docker-entrypoint-initdb.d/init-mariadb.sql

  sqldatabase:
    image: mariadb:11
    networks:
      - db-net
    environment:
      MARIADB_DATABASE: myrames-prod-db
      MARIADB_USER_FILE: /run/secrets/maria_user
      MARIADB_PASSWORD_FILE: /run/secrets/maria_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/maria_root_password
    ports:
      - 3306:3306
    volumes:
      - sqldb-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--connect" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    secrets:
      - maria_user
      - maria_password
      - maria_root_password

  phpmyadmin:
    image: phpmyadmin:5
    profiles:
      - dev-tool
    depends_on:
      - sqldatabase
    restart: always
    environment:
      PMA_HOST: sqldatabase
      PMA_PORT: 3306
      PMA_USER_FILE: /run/secrets/maria_user
      PMA_PASSWORD_FILE: /run/secrets/maria_password
    ports:
      - "127.0.0.1:8888:80"
    networks:
      - db-net
    secrets:
      - maria_user
      - maria_password

  broker:
    image: rabbitmq:3.12
    networks:
      - broker-net
    container_name: broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_PASS: brokerpass
      RABBITMQ_DEFAULT_USER: brokerusr
    restart: always
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_stomp &&
             rabbitmq-plugins enable rabbitmq_management &&
             rabbitmq-server"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  nosqldatabase:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - history-db:/data/db
    networks:
      - db-net
    ports:
      - 27017:27017
    restart: always
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 10
    secrets:
      - mongo_root_username
      - mongo_root_password
    configs:
      - source: init-nosql-db
        target: /docker-entrypoint-initdb.d/init-mongo.js

  mongo-express:
    image: mongo-express
    profiles:
      - dev-tool
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=nosqldatabase
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME_FILE=/run/secrets/mongo_root_username
      - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/mongo_root_password
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_BASICAUTH_USERNAME_FILE=/run/secrets/mongo_root_username
      - ME_CONFIG_BASICAUTH_PASSWORD_FILE=/run/secrets/mongo_root_password
    secrets:
      - mongo_root_username
      - mongo_root_password
    networks:
      - db-net
    volumes:
      - ./RESTApi/config.py:/app/config.py:ro

  wsapi:
    image: maven:3.9-amazoncorretto-21
    container_name: wsapi
    volumes:
      - ./LogisticoTrain_codebase/RealtimeAPI:/usr/src/RealtimeAPI
      - ./maven_cache:/root/.m2
    working_dir: /usr/src/RealtimeAPI
    command: >
      sh -c "mvn spring-boot:run"
    depends_on:
      sqldatabase:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - broker-net
      - db-net
    ports:
      - "8080:8080"

  front:
    image: nginx:1.25-alpine
    restart: always
    depends_on:
      - restapi
      - wsapi
    ports:
      - 80:80
    volumes:
      - ./vendorConfigurations/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/build:/var/www/app:ro
    networks:
      - db-net
      - broker-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  webapp:
    image: node:22-alpine
    profiles:
      - build
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    command: [ "npm", "run", "build" ]

networks:
  broker-net:
  db-net:


volumes:
  sqldb-data:
  history-db:


configs:
  init-nosql-db:
    file: ./init-mongo.js
  init-sql-db:
    file: ./init-mariadb.sql

secrets:
  mongo_root_username:
    file: ./secrets/mongo_root_username.txt
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt
  maria_user:
    file: ./secrets/maria_user.txt
  maria_password:
    file: ./secrets/maria_password.txt
  maria_root_password:
    file: ./secrets/maria_root_password.txt